resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:kdeng/concourse-schedule-middleman.git
    branch: master
    private_key: {{github-private-key}}
    skip_ssl_verification: true
    git_config:
    - name: http.sslVerify
      value: false
    
- name: every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: ci_update_version
  plan:
  - get: every-1m
    trigger: true

  - get: source-code
    trigger: true

  - task: artifact-deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bravissimolabs/alpine-git
          tag: latest
      inputs:
        - name: source-code
      outputs:
        - name: source-code-modified
      run:
        path: source-code/scripts/build.sh

  - put: source-code
    params: 
      repository: source-code-modified
    
    
