---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: ambassador-map-nginx
spec:
  prefix: /nginx/
  service: nginx-demo-service.default:9092
  # timeout_ms: 4000
  # idle_timeout_ms: 500000
  # connect_timeout_ms: 4000
  rewrite: "/"
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: ambassador-map-app
spec:
  prefix: /app/
  service: app-demo-service.default:9091
  # timeout_ms: 4000
  # idle_timeout_ms: 500000
  # connect_timeout_ms: 4000
  rewrite: "/"
  # labels:
  #   ambassador:
  #     - request_label:
  #       - backend
